#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDFinanciera")]
public partial class ClienteCorrienteDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertClienteCorriente(ClienteCorriente instance);
  partial void UpdateClienteCorriente(ClienteCorriente instance);
  partial void DeleteClienteCorriente(ClienteCorriente instance);
  #endregion
	
	public ClienteCorrienteDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDFinancieraConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ClienteCorrienteDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ClienteCorrienteDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ClienteCorrienteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ClienteCorrienteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ClienteCorriente> ClienteCorriente
	{
		get
		{
			return this.GetTable<ClienteCorriente>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClienteCorriente")]
public partial class ClienteCorriente : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _numeroTarjeta;
	
	private string _tipoTarjeta;
	
	private string _nombreUsuario;
	
	private int _mesExpiracion;
	
	private int _anoExpiracion;
	
	private string _email;
	
	private float _cupo;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumeroTarjetaChanging(string value);
    partial void OnnumeroTarjetaChanged();
    partial void OntipoTarjetaChanging(string value);
    partial void OntipoTarjetaChanged();
    partial void OnnombreUsuarioChanging(string value);
    partial void OnnombreUsuarioChanged();
    partial void OnmesExpiracionChanging(int value);
    partial void OnmesExpiracionChanged();
    partial void OnanoExpiracionChanging(int value);
    partial void OnanoExpiracionChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncupoChanging(float value);
    partial void OncupoChanged();
    #endregion
	
	public ClienteCorriente()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroTarjeta", DbType="NVarChar(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string numeroTarjeta
	{
		get
		{
			return this._numeroTarjeta;
		}
		set
		{
			if ((this._numeroTarjeta != value))
			{
				this.OnnumeroTarjetaChanging(value);
				this.SendPropertyChanging();
				this._numeroTarjeta = value;
				this.SendPropertyChanged("numeroTarjeta");
				this.OnnumeroTarjetaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoTarjeta", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string tipoTarjeta
	{
		get
		{
			return this._tipoTarjeta;
		}
		set
		{
			if ((this._tipoTarjeta != value))
			{
				this.OntipoTarjetaChanging(value);
				this.SendPropertyChanging();
				this._tipoTarjeta = value;
				this.SendPropertyChanged("tipoTarjeta");
				this.OntipoTarjetaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreUsuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string nombreUsuario
	{
		get
		{
			return this._nombreUsuario;
		}
		set
		{
			if ((this._nombreUsuario != value))
			{
				this.OnnombreUsuarioChanging(value);
				this.SendPropertyChanging();
				this._nombreUsuario = value;
				this.SendPropertyChanged("nombreUsuario");
				this.OnnombreUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesExpiracion", DbType="Int NOT NULL")]
	public int mesExpiracion
	{
		get
		{
			return this._mesExpiracion;
		}
		set
		{
			if ((this._mesExpiracion != value))
			{
				this.OnmesExpiracionChanging(value);
				this.SendPropertyChanging();
				this._mesExpiracion = value;
				this.SendPropertyChanged("mesExpiracion");
				this.OnmesExpiracionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoExpiracion", DbType="Int NOT NULL")]
	public int anoExpiracion
	{
		get
		{
			return this._anoExpiracion;
		}
		set
		{
			if ((this._anoExpiracion != value))
			{
				this.OnanoExpiracionChanging(value);
				this.SendPropertyChanging();
				this._anoExpiracion = value;
				this.SendPropertyChanged("anoExpiracion");
				this.OnanoExpiracionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cupo", DbType="Real NOT NULL")]
	public float cupo
	{
		get
		{
			return this._cupo;
		}
		set
		{
			if ((this._cupo != value))
			{
				this.OncupoChanging(value);
				this.SendPropertyChanging();
				this._cupo = value;
				this.SendPropertyChanged("cupo");
				this.OncupoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
