#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OPRSDB")]
public partial class PropietarioDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertPROPIETARIO(PROPIETARIO instance);
  partial void UpdatePROPIETARIO(PROPIETARIO instance);
  partial void DeletePROPIETARIO(PROPIETARIO instance);
  #endregion
	
	public PropietarioDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OPRSDBConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public PropietarioDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PropietarioDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PropietarioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PropietarioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<PROPIETARIO> PROPIETARIO
	{
		get
		{
			return this.GetTable<PROPIETARIO>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROPIETARIO")]
public partial class PROPIETARIO : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _ID;
	
	private string _NOMBRE;
	
	private string _APELLIDO;
	
	private System.Nullable<decimal> _CEDULA;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnAPELLIDOChanging(string value);
    partial void OnAPELLIDOChanged();
    partial void OnCEDULAChanging(System.Nullable<decimal> value);
    partial void OnCEDULAChanged();
    #endregion
	
	public PROPIETARIO()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(38,0) NOT NULL", IsPrimaryKey=true)]
	public decimal ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NChar(50)")]
	public string NOMBRE
	{
		get
		{
			return this._NOMBRE;
		}
		set
		{
			if ((this._NOMBRE != value))
			{
				this.OnNOMBREChanging(value);
				this.SendPropertyChanging();
				this._NOMBRE = value;
				this.SendPropertyChanged("NOMBRE");
				this.OnNOMBREChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO", DbType="NChar(20)")]
	public string APELLIDO
	{
		get
		{
			return this._APELLIDO;
		}
		set
		{
			if ((this._APELLIDO != value))
			{
				this.OnAPELLIDOChanging(value);
				this.SendPropertyChanging();
				this._APELLIDO = value;
				this.SendPropertyChanged("APELLIDO");
				this.OnAPELLIDOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA", DbType="Decimal(38,0)")]
	public System.Nullable<decimal> CEDULA
	{
		get
		{
			return this._CEDULA;
		}
		set
		{
			if ((this._CEDULA != value))
			{
				this.OnCEDULAChanging(value);
				this.SendPropertyChanging();
				this._CEDULA = value;
				this.SendPropertyChanged("CEDULA");
				this.OnCEDULAChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
