<?xml version="1.0" encoding="utf-8"?><Database Name="OPRSDB" Class="PropiedadDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=OPRSDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OPRSDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PROPIEDAD" Member="PROPIEDAD">
    <Type Name="PROPIEDAD">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(38,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Propietario" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Renta" Type="System.Decimal" DbType="Decimal(30,0) NOT NULL" CanBeNull="false" />
      <Column Name="Localidad" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NCuartos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>